local colors = require("colors")

require("modules.monitors")
require("modules.binds")
require("modules.autostart")
require("modules.env")
require("modules.looknfeel")
require("modules.misc")
require("modules.input")
require("modules.windowrules")
require("modules.layout")