#!/usr/bin/env bash

# === CONFIG ===
WAL_CACHE="$HOME/.cache/wal/colors.json"
WAYBAR_DIR="$HOME/.config/waybar"
WAYBAR_COLORS="$WAYBAR_DIR/colors.css"

# Extract colors from pywal JSON
BG=$(jq -r '.special.background' "$WAL_CACHE")
FG=$(jq -r '.special.foreground' "$WAL_CACHE")
ACCENT=$(jq -r '.colors.color1' "$WAL_CACHE")

# Fallback colors (if any field is null)
[ "$BG" = "null" ] && BG="#1e1e2e"
[ "$FG" = "null" ] && FG="#cdd6f4"
[ "$ACCENT" = "null" ] && ACCENT="#b4befe"

# Write GTK-style Waybar color variables
cat > "$WAYBAR_COLORS" <<EOF
/* Auto-generated by pywal */
@define-color bg ${BG};
@define-color fg ${FG};
@define-color accent ${ACCENT};
EOF

# === RELOAD EVERYTHING ===

# Reload Waybar
pkill waybar && waybar &

# Reload Kitty colors (if Kitty is running)
kitty @ set-colors -a ~/.cache/wal/colors-kitty.conf 2>/dev/null

# Optional: Reload GTK theme (if wal-gtk is installed)
if command -v wal-gtk &>/dev/null; then
    wal-gtk --theme "$WAL_CACHE"
fi

echo "✅ Waybar and terminal theme updated!"
