#!/usr/bin/env bash
# Hyprland Theme Switcher by Matrix & GPT-5
# Random wallpaper + Pywal colors + Waybar + Kitty auto-sync

# === CONFIG ===
WALLPAPER_DIR="$HOME/Pictures/wallpapers/"
WAYBAR_DIR="$HOME/.config/waybar"
WAL_CACHE="$HOME/.cache/wal/colors.json"
WAYBAR_COLORS="$WAYBAR_DIR/colors.css"

# === RANDOM WALLPAPER SELECTION ===
WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" \) | shuf -n 1)
if [[ -z "$WALLPAPER" ]]; then
    echo "No wallpapers found in $WALLPAPER_DIR"
    exit 1
fi

# === APPLY WALLPAPER ===
if command -v swww &>/dev/null; then
    swww img "$WALLPAPER" --transition-type any --transition-duration 2
else
    pkill swaybg 2>/dev/null
    swaybg -i "$WALLPAPER" &
fi

# === GENERATE COLOR SCHEME WITH PYWAL ===
wal -i "$WALLPAPER" -n

# === READ COLORS ===
BG=$(jq -r '.special.background' "$WAL_CACHE")
FG=$(jq -r '.special.foreground' "$WAL_CACHE")
ACCENT=$(jq -r '.colors.color1' "$WAL_CACHE")

# Fallbacks if wal fails
[ "$BG" = "null" ] && BG="#1e1e2e"
[ "$FG" = "null" ] && FG="#cdd6f4"
[ "$ACCENT" = "null" ] && ACCENT="#b4befe"

# === WRITE WAYBAR COLORS ===
cat > "$WAYBAR_COLORS" <<EOF
/* Auto-generated by pywal */
@define-color bg ${BG};
@define-color fg ${FG};
@define-color accent ${ACCENT};
EOF

# === APPLY THEMES ===
# Reload Waybar
if pgrep -x waybar >/dev/null; then
    pkill waybar
    sleep 0.3
fi
waybar &

# Reload Kitty
if command -v kitty &>/dev/null; then
    kitty @ set-colors -a ~/.cache/wal/colors-kitty.conf 2>/dev/null
fi

# Reload GTK (optional)
if command -v wal-gtk &>/dev/null; then
    wal-gtk --theme "$WAL_CACHE"
fi

# === DONE ===
echo "Wallpaper changed: $(basename "$WALLPAPER")"
echo "Theme synced across Waybar, Kitty, and GTK!"
