[ColorScheme]
author=Matugen
name=matugen

# Window backgrounds
window=#1a120e
windowText=#f1dfd8
base=#1a120e
text=#f1dfd8
tooltipBase=#322824
tooltipText=#f1dfd8

# Buttons
button=#271e1a
buttonText=#f1dfd8
brightText=#ffb694

# Selection
highlight=#703718
highlightedText=#ffdbcc

# Links
link=#ffb694
linkVisited=#e6bead

# Alternate
alternateBase=#271e1a

# Foreground
foreground=#f1dfd8

# Background
background=#1a120e
