#!/usr/bin/env bash
# Bluetooth device selector — Matugen themed

ROFI_THEME="$HOME/.config/rofi/dmenu.rasi"
FONT="JetBrainsMono Nerd Font 10"

bluetoothctl scan on >/dev/null 2>&1 &
sleep 2

device=$(bluetoothctl devices \
| cut -d' ' -f3- \
| rofi -dmenu -theme "$ROFI_THEME" -p "Bluetooth" -font "$FONT")

pkill -f "bluetoothctl scan"

[ -z "$device" ] && exit

mac=$(bluetoothctl devices | grep "$device" | awk '{print $2}')

bluetoothctl connect "$mac"
